python3 brs_gan.py --dir="mnist_smooth_alpha_1000_loss1_sigma" --alpha=1000 --l=1 --mode="smooth" --sigma=1&
python3 brs_gan.py --dir="mnist_smooth_alpha_100_loss1_sigma" --alpha=100 --l=1 --mode="smooth" --sigma=1&
python3 brs_gan.py --dir="mnist_smooth_alpha_10_loss1_sigma" --alpha=10 --l=1 --mode="smooth" --sigma=1&
python3 brs_gan.py --dir="mnist_smooth_alpha_1_loss1_sigma" --alpha=1 --l=1 --mode="smooth" --sigma=1&
python3 brs_gan.py --dir="mnist_smooth_alpha_01_loss1_sigma" --alpha=0.1 --l=1 --mode="smooth" --sigma=1&
python3 brs_gan.py --dir="mnist_smooth_alpha_001_loss1_sigma" --alpha=0.01 --l=1 --mode="smooth" --sigma=1&
python3 brs_gan.py --dir="mnist_smooth_alpha_0001_loss1_sigma" --alpha=0.001 --l=1 --mode="smooth" --sigma=1&
python3 brs_gan.py --dir="mnist_smooth_alpha_1000_loss1_nosigma" --alpha=1000 --l=1 --mode="smooth" --sigma=0&
python3 brs_gan.py --dir="mnist_smooth_alpha_100_loss1_nosigma" --alpha=100 --l=1 --mode="smooth" --sigma=0&
python3 brs_gan.py --dir="mnist_smooth_alpha_10_loss1_nosigma" --alpha=10 --l=1 --mode="smooth" --sigma=0&
python3 brs_gan.py --dir="mnist_smooth_alpha_1_loss1_nosigma" --alpha=1 --l=1 --mode="smooth" --sigma=0&
python3 brs_gan.py --dir="mnist_smooth_alpha_01_loss1_nosigma" --alpha=0.1 --l=1 --mode="smooth" --sigma=0&
python3 brs_gan.py --dir="mnist_smooth_alpha_001_loss1_nosigma" --alpha=0.01 --l=1 --mode="smooth" --sigma=0&
python3 brs_gan.py --dir="mnist_smooth_alpha_0001_loss1_nosigma" --alpha=0.001 --l=1 --mode="smooth" --sigma=0&
